import React, { useEffect } from 'react';
import { AlertTriangle, ArrowLeft, ShieldCheck, CheckCircle2, FileText } from 'lucide-react';

interface DisclaimerPageProps {
  onBackToGenerator: () => void;
  onOpenTerms: () => void;
}

export const DisclaimerPage: React.FC<DisclaimerPageProps> = ({
  onBackToGenerator,
  onOpenTerms
}) => {
  useEffect(() => {
    document.title = "Legal Disclaimer – Synthetic & Mock Data Notice | Vib Tools";
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  return (
    <div className="min-h-screen bg-slate-50/70 dark:bg-slate-950 text-slate-800 dark:text-slate-100 font-sans transition-colors">
      
      {/* Breadcrumb Header */}
      <div className="sticky top-12 sm:top-13 z-30 border-b border-slate-200/80 dark:border-slate-800 bg-white/95 dark:bg-slate-900/95 backdrop-blur-md px-3 sm:px-6 py-2.5">
        <div className="max-w-4xl mx-auto flex items-center justify-between text-xs">
          <div className="flex items-center gap-2">
            <button
              onClick={onBackToGenerator}
              className="inline-flex items-center gap-1 text-slate-500 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 font-medium cursor-pointer"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Generator</span>
            </button>
            <span className="text-slate-300 dark:text-slate-700">/</span>
            <span className="text-blue-600 dark:text-blue-400 font-semibold">Legal Disclaimer</span>
          </div>
          <button
            onClick={onBackToGenerator}
            className="px-3 py-1 text-[11px] font-semibold text-white bg-blue-600 hover:bg-blue-700 rounded-md transition-all cursor-pointer shadow-2xs"
          >
            Launch Tool
          </button>
        </div>
      </div>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-8 sm:py-12 space-y-8">
        
        {/* Header */}
        <header className="space-y-3 pb-6 border-b border-slate-200/80 dark:border-slate-800">
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-50 dark:bg-amber-950/70 text-amber-700 dark:text-amber-400 border border-amber-200/70 dark:border-amber-800 text-xs font-semibold">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>Important Legal Notice</span>
          </div>
          <h1 className="text-2xl sm:text-4xl font-extrabold tracking-tight text-slate-900 dark:text-white">
            Synthetic &amp; Mock Data Legal Disclaimer
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Last Updated: September 23, 2026 · Vib Tools Legal &amp; Compliance
          </p>
        </header>

        {/* Warning Banner */}
        <div className="p-4 rounded-xl border border-amber-300 dark:border-amber-700 bg-amber-50/80 dark:bg-amber-950/40 space-y-2">
          <h3 className="font-bold text-xs sm:text-sm text-amber-950 dark:text-amber-200 flex items-center gap-1.5">
            <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0" />
            <span>All Data is 100% Synthetic &amp; Fictitious</span>
          </h3>
          <p className="text-xs text-amber-900 dark:text-amber-300 leading-relaxed">
            All names, street addresses, telephone numbers, Social Security Numbers (SSNs), and credit card credentials synthesized by Vib Tools Fake Name Generator are randomly created algorithmic artifacts. Any resemblance to actual persons, living or dead, real credit accounts, or actual physical residences is purely coincidental.
          </p>
        </div>

        <article className="space-y-8 text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
          
          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white">
              1. Non-Transactional Payment Card Numbers
            </h2>
            <p>
              Credit card numbers generated by this tool (Visa, Mastercard, American Express) are computed using the ISO/IEC 7812 Luhn Modulo 10 check algorithm for frontend format validation only.
            </p>
            <p className="font-semibold text-rose-600 dark:text-rose-400">
              These card numbers have no monetary balance, are NOT linked to any financial institution or merchant account, and cannot be used to execute purchases or transfer funds.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white">
              2. Social Security Numbers (SSN) &amp; Government Identifiers
            </h2>
            <p>
              US Social Security numbers generated utilize reserved non-issuance ranges (such as area numbers starting with 900–999 or invalid groups) adhering to official SSA standards. They do not belong to real citizens and cannot be used for taxation, credit scores, or identity verification.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white">
              3. Limitation of Liability
            </h2>
            <p>
              Under no circumstances shall Vib Tools, its maintainers, or contributors be held liable for any direct, indirect, incidental, or punitive damages arising from the use or misuse of the data generated by this service. Users assume all responsibility for compliance with local and international laws when handling test data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white">
              4. Service Intended Solely for Testing &amp; Development
            </h2>
            <p>
              This website exists to assist software engineers, QA analysts, database administrators, and creative writers in their daily legitimate workflows.
            </p>
          </section>

        </article>

      </main>
    </div>
  );
};
